version = 0.1
[default.deploy.parameters]
stack_name = "sam-dynamo-vehicle"
s3_prefix = "sam-dynamo-vehicle"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Prefix=\"sam-dynamo-vehicle\""
image_repositories = []
resolve_s3 = true
